import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//import {Providers} from './redux/providers'
import {Providers} from '../reduxts/provider'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spaceship Language',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        {children}
        </Providers>
       
        <ToastContainer
        position="top-center"
        autoClose={1000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        pauseOnFocusLoss
        draggable
      />
        
        
        
        </body>
    </html>
  )
}
